baseurl = "https://radubahmata.com"
title = "radubahmata"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
animateStyle = "animated zoomIn fast"

[params.social]
twitter = "BowTiedRadone"
github = "BowTiedRadone"
email = "bowtiedradone@gmail.com"

[[params.navlinks]]
name = "about/"
url = "about/"

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "series/"
url = "series/"
